### ISSUE TITLE
Tables lacking row headers make them less accessible

### ISSUE THREAD

**Issue by selfthinker** [alphagov/govspeak#110]
Lots of tables on gov.uk are less accessible because they don't have row headers (i.e. a `th` as the first cell(s) in a row). If a cell cannot be understood without the context of the column header and/or row header, it is a barrier for screen reader users. Some tables need column headers, some need row headers and some need both, depending on context.

The main reason for missing row headers is that govspeak (or markdown/kramdown) doesn't support it.
(Whenever any Markdown flavour is asked to implement it, their usual response is "Use HTML!" even though an additional `th` syntax wouldn't make things much more complex and the majority of other plain text markup languages have a specific syntax for `th`s.)

A good syntax for a new implementation (either via a kramdown extension or a govspeak hack) I would like to propose is to add a `#` after the pipe. Using a `#` would be intuitive as it's already used for headings. For example:

```
|                 |# Second Column  |# Third Column          |
| :-------------- | :-------------: | ---------------------: |
|# First row      | Cell            | Very long data entry   |
|# Second row     | Cell            | Cell                   |
|# Third row      | Cell that spans across two columns      ||
```

(This example also includes a proposed syntax for merging cells, the second most needed feature to make govspeak tables more accessible.)

**Comment by accessiblewebuk** [comment]
More flexibility with table headers is definitely needed - without appropriate column and row headers in a table, the table becomes inaccessible, particularly if it large or contains complex information. 

A simple change to syntax like above would be really useful. 

It would need to be flexible enough to allow for the fact that row headers aren't necessarily in the first column, would need guidance to ensure content editors know when to use row headers and where and when to use spanning columns.

**Comment by selfthinker** [comment]
We were working on some guidance for when to add row headers and when column headers and other things around tables late 2016. But it never got published because it's not possible to do in Govspeak.
I agree that guidance is necessary. When I did some user research with content editors to create tables, the biggest outcome was that how to structure tables is very hard to understand.
