### ISSUE TITLE
kramdown gem is locked to ~> 1.15.0

### ISSUE THREAD

**Issue by alexey-klimuk** [alphagov/govspeak#183]
Hi guys, 

The kramdown gem is locked to version 1.15.0 but there is a high severity vulnerability and it's recommended to update it to 2.3.0

https://app.snyk.io/vuln/SNYK-RUBY-KRAMDOWN-585939

**Comment by matthewford** [comment]
Closed by https://github.com/alphagov/govspeak/pull/189

**Comment by alexey-klimuk** [comment]
Thanks @kevindew 👍
