### ISSUE TITLE
URI Gotcha with Ruby 2.2.x

### ISSUE THREAD

**Issue by jamiecobbett** [alphagov/govspeak#57]
Applications using this gem need to take care when upgrading to Ruby 2.2.x as it is less tolerant of non-standard URIs and so new and existing content might no longer be parseable by Govspeak.

More detail:

Ruby 2.2 [upgrades the `URI` module](https://github.com/ruby/ruby/blob/v2_2_0/NEWS#L238-L239) in stdlib to support [RFC3986](https://www.ietf.org/rfc/rfc3986.txt). This is a stricter form of `URI.parse` and means that anywhere we parse URIs that might be invalid, an error will be raised.

Examples found so far include:

* `mailto://address` links (raises `NoMethodError: undefined method 'split' for nil:NilClass`
* blank `mailto:` (raises `NoMethodError: undefined method 'split' for nil:NilClass`)
* URLs with trailing spaces (raises `URI::InvalidURIError: bad URI(is not URI?)`)

This may or may not be something we can/should fix in Govspeak. The alternative is to be aware when upgrading apps using Govspeak to fix existing content.

@boffbowsh did the hard work to figure this out. For more information, see: https://github.com/alphagov/whitehall/pull/2234

**Comment by tekin** [comment]
One option is to use `[Addressable::URI](http://addressable.rubyforge.org/api/Addressable/URI.html)` instead of `URI` - it's less strict when parsing URIs.

**Comment by h-lame** [comment]
Is there any desire to do what @tekin suggests and replace `URI.parse` with `Addressable::URI.parse` to avoid unexpected exceptions?

**Comment by jamiecobbett** [comment]
Fixed in [3.5.1](https://github.com/alphagov/govspeak/pull/63).
