### ISSUE TITLE
Should `{::reverse}{:/reverse}` be removed?

### ISSUE THREAD

**Issue by fofr** [alphagov/govspeak#62]
We currently allow content editors to reverse their text using:
`{::reverse}This text will be reversed{:/reverse}`

It looks like this was the first extension to be added, but the commit doesn't give context for its use: https://github.com/alphagov/govspeak/commit/4117770acc24b9b4ab07fd54172f3206573fba52

My guess would be that this is a hangover from some early govspeak tests. Unless anyone can provide some light on it?

Has it been used anywhere?

**Comment by bradwright** [comment]
I can't imagine any reason for this to exist.
